name: Auto Merge Dev to Main

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  merge-to-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/dev -m "Auto-merge dev into main"
          git push origin main