name: Auto Merge Dev to Main

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  merge-to-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch main and dev branches
        run: |
          git fetch origin main
          git fetch origin dev

      - name: Merge dev into main
        run: |
          git checkout main
          
          git merge origin/dev -X theirs --allow-unrelated-histories -m "Auto-merge dev into main"
      
      - name: Push changes to main
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git push origin main